### ISSUE TITLE
feat: implement End-to-End Testing

### ISSUE THREAD

**Issue by jma49** [jma49/ITMD-536-Group3-Project#2]
Set up end-to-end testing using a tool like Playwright or Cypress. Include basic tests to cover key user flows in the application.

**Comment by abhirambj** [comment]
are you working on this? @jma49

**Comment by jma49** [comment]
not yet

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Abhiram B J ***@***.***>
Sent: Wednesday, November 20, 2024 10:02:51 AM
To: jma49/ITMD-536-Group3-Project ***@***.***>
Cc: Jincheng ***@***.***>; Mention ***@***.***>
Subject: [Ext] Re: [jma49/ITMD-536-Group3-Project] feat: implement End-to-End Testing (Issue #2)


are you working on this? @jma49<https://github.com/jma49>

**Comment by abhirambj** [comment]
do you want me to work on it or will u work on it?

**Comment by jma49** [comment]
you can work on it. make a pr.

Get Outlook for iOS<https://aka.ms/o0ukef>
________________________________
From: Abhiram B J ***@***.***>
Sent: Wednesday, November 20, 2024 12:09:51 PM
To: jma49/ITMD-536-Group3-Project ***@***.***>
Cc: Jincheng ***@***.***>; Mention ***@***.***>
Subject: [Ext] Re: [jma49/ITMD-536-Group3-Project] feat: implement End-to-End Testing (Issue #2)


do you want me to work on it or will u work on it?

**Comment by jma49** [comment]
> do you want me to work on it or will u work on it?

I suggest you fullfill Cypress on the project.

**Comment by abhirambj** [comment]
ok will use cypress...

**Comment by abhirambj** [comment]
will work on the issue mentioned..
